name: Java CI with Maven in Develop

on:
  push:
    branches:
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
  
  deploy-development:
    needs: build
    runs-on: ubuntu-latest
    env:
      APPLICATION_NAME: "poc-app"
    steps:
      - name: Deploy to Development
        run: echo "Deploying to development $APPLICATION_NAME"
